spring:
  datasource:
    url: jdbc:mysql://localhost:3306/slamracing_db?createDatabaseIfNotExist=true
    username: root
    password: j0s33nr1qu3
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    web: debug
    sql: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'